### ISSUE TITLE
oath token issue

### ISSUE THREAD

**Issue by compadvance** [michabbb/php-ebay-sdk#2]
Hi , How you pass oath token to the shopping API ? 
I was looking for something like     

public function setEBayAuthToken(?string $eBayAuthToken = null): self

which has been implemented for that purpose in src_trading/StructType  for trading API , 
any hints would be much appreciated , 
Thanks for looking at it 
Emil

**Comment by michabbb** [comment]
hi, 
this SDK does not support the oauth token, sorry.
it only supports the 'auth'n'auth token, without the (unnecessary) overhead that comes with oauth.
are you working for a seller (or more) or is your app something that provides a "login with ebay" button ? 😏

**Comment by michabbb** [comment]
ah sorry, i forgot 😁 ebay changed that..... shopping only works with oauth.... that sucks.... let me see.....

**Comment by michabbb** [comment]
i guess, somewhere at this point:

https://github.com/michabbb/php-ebay-sdk/blob/php8/base.php#L118

you could just try to add something like, you already see here:

https://github.com/michabbb/php-ebay-sdk/blob/php8/base.php#L102

so in our case, it would be:

```php
if ((string)$this->Service==='macropage\ebaysdk\shopping\ServiceType\Service') {
    $this->Service->setHttpHeader('X-EBAY-API-IAF-TOKEN', $this->appid);
}
```
"appid" would be your "application access token".
"appid" is the wrong wording, but I keep it here, because of this line:

https://github.com/michabbb/php-ebay-sdk/blob/php8/test.php#L25

does this help ? 😏

**Comment by compadvance** [comment]
Thanks mate , it helps indeed , 
no error anymore but response now looks like : 
object(macropage\ebaysdk\shopping\StructType\GetSingleItemRequestType)#115 (6) {
  ["ItemID":protected]=>
  string(12) "334664496876"
  ["VariationSKU":protected]=>
  string(7) "Details"
  ["VariationSpecifics":protected]=>
  NULL
  ["IncludeSelector":protected]=>
  NULL
  ["MessageID":protected]=>
  NULL
  ["any":protected]=>
  NULL
}
not receiving any details from API despite item ID

**Comment by compadvance** [comment]
and when as such object being used to call $item = $ShoppingService->GetSingleItem($SingleItemRequestType);

 Exception: Bad Request

EbayAPIs/php-ebay-sdk-php7/src_shopping/ServiceType/Service.php', line 139.

**Comment by compadvance** [comment]
Thats the request : 
[2023-01-24T12:16:49.256360+00:00] name.DEBUG: Request {"url":"","name":"GetSingleItem","headers_request":"POST /shopping?callname=GetSingleItem&siteid=3&appid=################## token #################&version=1199&routing=new HTTP/1.1\r\nHost: open.api.ebay.com\r\nConnection: Keep-Alive\r\nUser-Agent: PHP-SOAP/7.4.29\r\nContent-Type: text/xml; charset=utf-8\r\nSOAPAction: \"\"\r\nContent-Length: 365\r\nX-EBAY-API-IAF-TOKEN: ################## token #################\r\n\r\n","headers_response":"HTTP/1.1 400 Bad Request\r\ndate: Tue, 24 Jan 2023 12:16:49 GMT\r\nserver: ebay-proxy-server\r\nconnection: close\r\ncontent-length: 0\r\n","request_xml":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ns1=\"urn:ebay:apis:eBLBaseComponents\">\n  <SOAP-ENV:Header/>\n  <SOAP-ENV:Body>\n    <ns1:GetSingleItemRequest>\n      <ns1:ItemID>334664496876</ns1:ItemID>\n      <ns1:VariationSKU>Details</ns1:VariationSKU>\n    </ns1:GetSingleItemRequest>\n  </SOAP-ENV:Body>\n</SOAP-ENV:Envelope>\n","response_xml":null,"last_error":{"macropage\\ebaysdk\\shopping\\ServiceType\\Service::GetSingleItem":"[object] (SoapFault(code: 0 faultcode: HTTP): 


Bad Request at /EbayAPIs/php-ebay-sdk-php7/src_shopping/ServiceType/Service.php:139)"},"faultstring":"Bad Request","faultstring_detail":null} []

**Comment by michabbb** [comment]
oh sorry... i forgot that the "app-id" is used in the URL as you can see in your logs:

https://github.com/michabbb/php-ebay-sdk/blob/6bed0ea37aa3d7ae0fb1dbd0567305c776fef5a5/base.php#L127

🤔 I don´t use the shopping API anymore, so can you please remove `'&appid=' . $this->appid ` in that line from the URL and make a test?
the trading API still needs that parameter, but only for testing the shopping API, please remove it and let me know.

maybe the shopping API does not need the "appid" in the URL any longer, because you are using the oauth token in the header, but I am not sure. in case you still get an error without "appid" in the URL, please put it back in but please
replace `'&appid=' . $this->appid ` with `&appid=<your real application id>` from your app.

**Comment by compadvance** [comment]
Hi mate , after removing appid from url : 
object(macropage\ebaysdk\shopping\StructType\GetSingleItemResponseType)#124 (7) {
  ["Item":protected]=>
  NULL
  ["Timestamp":protected]=>
  string(24) "2023-01-24T19:24:10.754Z"
  ["Ack":protected]=>
  string(7) "Failure"
  ["Errors":protected]=>
  array(1) {
    [0]=>
    object(macropage\ebaysdk\shopping\StructType\ErrorType)#111 (8) {
      ["ShortMessage":protected]=>
      string(25) "Variation does not exist."
      ["LongMessage":protected]=>
      string(102) "The item contains no variation matching variation label or VariationSpecifics included in the request."
      ["ErrorCode":protected]=>
      string(5) "10.89"
      ["UserDisplayHint":protected]=>
      NULL
      ["SeverityCode":protected]=>
      string(5) "Error"
      ["ErrorParameters":protected]=>
      array(0) {
      }
      ["ErrorClassification":protected]=>
      string(12) "RequestError"
      ["any":protected]=>
      NULL
    }
  }
  ["Build":protected]=>
  string(28) "E1199_CORE_APILW_19146596_R1"
  ["Version":protected]=>
  string(4) "1199"
  ["CorrelationID":protected]=>
  NULL
}

**Comment by compadvance** [comment]
what you use instead of shopping API to get listing details / pics gallery ect ?

**Comment by michabbb** [comment]
hi, first of all, it looks like your authentification is now working, because you get a normal error that is related to your request, not to your way of authentification: "Variation does not exist.". so the error is about your request, please show it to me 😏 

to get all item info, why don´t you use the "GetItem" call of the trading API ? 🤔
